API/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.api_root, name='api-root'),
    path('register/', views.registration_view, name='api-register'),
    path('login/', views.ObtainAuthTokenView.as_view(), name='api-login'),
    path('users/', views.UserList.as_view(), name='api-users'),
    path('user/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile-detail'),
    path('languages/', views.LanguageList.as_view(), name='api-languages'),
    path('language/<int:pk>', views.LanguageDetail.as_view(), name='language-detail'),
    path('stage/<int:pk>', views.StageView.as_view(), name='stage-detail'),
    path('study-materials/<int:pk>', views.StudyMaterialView.as_view(), name='studymaterial-detail'),
    path('question/<int:pk>', views.QuestionView.as_view(), name='question-detail'),
    path('answer/<int:pk>', views.AnswerView.as_view(), name='answeroptions-detail'),
    path('result/<int:pk>', views.ResultView.as_view(), name='result-detail'),
    path('create_result/', views.create_result_view, name='create-result'),

]

language/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_view, name='home'),
    path('learn/', views.LearnView.as_view(), name='learn'),
    path('study-material/<int:pk>/', views.StudyView.as_view(), name='study'),
    path('analyze/<int:pk>', views.analyze, name='analyze'),
    path('languages/', views.LanguageView.as_view(), name='language'),
    path('manage/', views.ManageView.as_view(), name='manage'),
    path('language/<int:pk>', views.SingleLanguageView.as_view(), name='single'),
    path('reset/<int:pk>', views.reset_view, name='reset'),
    path('remove/<int:pk>', views.remove_view, name='remove'),
    path('add/<int:pk>', views.add_view, name='add'),
    path('register-single/<int:pk>', views.register_single_view, name='register-single'),
    path('search/', views.search_view, name='search'),
]

talku_talku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from user.forms import ResetForm, ResetConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('language.urls')),
    path('api/', include('API.urls')),
    path('user/', include('user.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html', form_class=ResetForm),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
    path('accounts/', include('allauth.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

language/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models import Q
from django.utils import timezone


class LanguageQuerySet(models.QuerySet):

    def search(self, query):
        lookup = (
            Q(name__icontains=query)
        )
        return self.filter(lookup)


class LanguageManager(models.Manager):
    def get_queryset(self):
        return LanguageQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)


class Language(models.Model):
    name = models.CharField(_('Name'), max_length=20, unique=True)
    brief_description = models.TextField(_('Brief Description'), blank=True)
    objects = LanguageManager()

    def __str__(self):
        return self.name


all_languages = Language.objects.all()


class Stage(models.Model):
    NUMBER = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        ('13', '13'),
        ('14', '14'),
        ('15', '15'),
        ('16', '16'),
        ('17', '17'),
        ('18', '18'),
        ('19', '19'),
        ('20', '20'),
    )

    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    number = models.CharField(_('Number'), max_length=2, choices=NUMBER)
    name = models.CharField(_('Name'), max_length=40)
    objects = models.Manager()

    class Meta:
        unique_together = (("language", "number"),)

    def __str__(self):
        return f'{self.name} ({self.language.name})'


class StudyMaterial(models.Model):
    stage = models.OneToOneField(Stage, on_delete=models.CASCADE)
    # language = models.ForeignKey(Language, on_delete=models.CASCADE)
    topic = models.CharField(_('Topic'), max_length=30)
    text = models.TextField(_('Topic Details'))
    audio = models.FileField(upload_to='audio', blank=True)
    date_created = models.DateTimeField(_('Date Created'), auto_now_add=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.topic} for {self.stage.language.name}'


class Question(models.Model):
    # language = models.ForeignKey(Language, on_delete=models.CASCADE)
    # stage = models.ForeignKey(Stage, on_delete=models.CASCADE)
    study_material = models.ForeignKey(StudyMaterial, on_delete=models.CASCADE)
    text = models.CharField(_('Question'), max_length=100)
    audio = models.FileField(upload_to='audio', blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return self.text


class AnswerOptions(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    options_text = models.CharField(max_length=50)
    is_correct = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return self.options_text


class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    study_material = models.ForeignKey(StudyMaterial, on_delete=models.CASCADE)
    score = models.IntegerField(_('Score'), default=0)
    objects = models.Manager()
    # answer = models.


# class Progress(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     languages = models.ForeignKey(Language, on_delete=models.CASCADE)
#     progress = models.IntegerField(default=0, validators=[
#             MaxValueValidator(100),
#             MinValueValidator(0)
#         ])
#     objects = models.Manager()


class SearchQuery(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    query = models.CharField(max_length=220)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query

language/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from user.models import Profile
from language.models import StudyMaterial, Question, AnswerOptions, Result, Language
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required
from .models import Language, SearchQuery
from django.contrib import messages


def home_view(request):
    return render(request, 'language/home.html')


class LearnView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'language/learn.html'
    context_object_name = 'languages'

    def get_queryset(self, **kwargs):
        profile = Profile.objects.get(user=self.request.user)
        languages = profile.languages.all()
        return languages

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Learn'
        return context


class StudyView(LoginRequiredMixin, DetailView):
    model = StudyMaterial
    template_name = 'language/study_material.html'
    context_object_name = 'material'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Study'
        result = Result.objects.filter(user=self.request.user, study_material=self.get_object()).first()
        if result:
            context['result'] = result
        return context


@login_required
def analyze(request, pk):
    material = get_object_or_404(StudyMaterial, pk=pk)
    if request.method == 'GET':
        return render(request, 'language/study_material.html', context={'material': material})
    else:
        answers = []
        score = 0
        questions = material.question_set.all()
        for question in questions:
            try:
                q = request.POST[str(question.id)]
            except MultiValueDictKeyError:
                messages.warning(request, f'Select a choice for all questions.')
                return redirect('study', pk=pk)
                # return render(request, 'language/study_material.html',
                #               context={'material': material, 'error': 'Select a choice for all questions'})
            answers.append(q)
        result = Result.objects.filter(user=request.user, study_material=material).first()
        if not result:
            result = Result.objects.create(user=request.user, study_material=material)
        for id in answers:
            answer = get_object_or_404(AnswerOptions, pk=id)
            if answer.is_correct:
                score += 1
        average = 0
        if len(answers) != 0:
            average = int((score/len(answers)) * 100)
        result.score = average
        result.save()
        return render(request, 'language/result.html', context={'object': result})


class LanguageView(LoginRequiredMixin, ListView):
    model = Language
    template_name = 'language/languages.html'
    context_object_name = 'languages'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Languages'
        return context

    def post(self, request, *args, **kwargs):
        input_languages = []
        for language in Language.objects.all():
            q = request.POST.get(f'option{language.id}')
            input_languages.append(q)
        for input_language in input_languages:
            if input_language:
                item = Language.objects.get(id=input_language)
                if item not in request.user.profile.languages.all():
                    request.user.profile.languages.add(item)
        request.user.profile.save()
        return redirect('learn')


class ManageView(LoginRequiredMixin, ListView):
    model = Language
    template_name = 'language/manage.html'
    context_object_name = 'languages'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Manage'
        return context


class SingleLanguageView(LoginRequiredMixin, DetailView):
    model = Language
    template_name = 'language/single-language.html'
    context_object_name = 'language'

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        if object not in request.user.profile.languages.all():
            return redirect('register-single', pk=object.pk)
        return render(request, 'language/single-language.html', context={'language': object})


@login_required
def reset_view(request, pk):
    results = request.user.result_set.all()
    language = get_object_or_404(Language, pk=pk)
    stages = language.stage_set.all()
    study_materials = []
    for stage in stages:
        study_materials.append(stage.studymaterial)
    for result in results:
        if result.study_material in study_materials:
            result.score = 0
            result.save()
    return redirect('manage')


@login_required
def remove_view(request, pk):
    language = get_object_or_404(Language, pk=pk)
    if language in request.user.profile.languages.all():
        request.user.profile.languages.remove(language)
        request.user.profile.save()
    return redirect('manage')


@login_required
def add_view(request, pk):
    language = get_object_or_404(Language, pk=pk)
    if language not in request.user.profile.languages.all():
        request.user.profile.languages.add(language)
        request.user.profile.save()
    return redirect('manage')


@login_required
def register_single_view(request, pk):
    language = get_object_or_404(Language, pk=pk)
    if language not in request.user.profile.languages.all():
        request.user.profile.languages.add(language)
        request.user.profile.save()
    return redirect('single', pk=pk)


def search_view(request):
    query = request.GET.get('q', None)
    user = None
    if request.user.is_authenticated:
        user = request.user
    context = {'query': query}
    if query is not None:
        SearchQuery.objects.create(user=user, query=query)
        result = Language.objects.search(query=query)
        context['objects'] = result
        context['query'] = query
        context['title'] = 'Search'
    return render(request, 'language/search.html', context)

language/templates/language/languages.html
{% extends "user/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="main_box">
        <h2 class="main_heading text-center main_heading_two">Which Language Do You Want To learn?</h2>
        <div class="log_form">
            <form action="" class="form my-5 py-5" method="POST">
                {% csrf_token %}
                {% for language in languages %}
                <div class="inputGroup">
                    <input id="option{{ language.id }}" name="option{{ language.id }}" type="checkbox" value="{{ language.id }}" />
                    <label for="option{{ language.id }}">{{ language.name }}</label>
                </div>
                {% endfor %}
<!--                <div class="inputGroup">-->
<!--                    <input id="option2" name="option2" type="checkbox" />-->
<!--                    <label for="option2">Igbo</label>-->
<!--                </div>-->
<!--                <div class="inputGroup">-->
<!--                    <input id="option3" name="option3" type="checkbox" />-->
<!--                    <label for="option3">Hausa</label>-->
<!--                </div>-->
                <button class="log_button btn">Sign Up</button>

            </form>
        </div>
    </div>
{% endblock content %}

language/templates/language/learn.html
{% extends "user/base.html" %}
{% load static %}
{% load custom_filter_tags %}
{% block content %}
<section class="content">
        <div class="first-text">
            <h1 class="lead">Learn</h1>
        </div>
    {% if not languages %}
    <h2>You have not registered for any language</h2>
    {% else %}
    {% for language in languages %}
        <div class="border-bottom mt-5">
            <a href="{% url 'single' language.id %}" style="color:black;"><h1>{{ language.name }}</h1></a>
        </div>
        <div class="mt-2">
            {% if language.brief_description %}
            <p>Description: {{ language.brief_description|shrink }}...<a href="{% url 'single' language.id %}">Click to See Full Course</a></p>
            {% endif %}
        </div>
        <div class="content_box d-flex">
            <div class="content_box_one">

                <div class="row">
                    {% for stage in language.stage_set.all %}
                    {% if forloop.counter < 4 %}
                    <div class="col-lg-4 col-md-6 col-sm-6 co-12 mb-4 c_box_cover">
                        <h3>{{ stage.studymaterial.topic }}</h3>
                        <a href="{% url 'study' stage.studymaterial.id %}">
                            <div class="c_box">
                                {{ stage.studymaterial.text|shrink }}...  <b> Click to learn</b>
                            </div>
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% with progress=user.result_set.all|calculate:language %}
            <div class="content_box_two">
                <div class="top d-flex align-items-end">
                    <div class="top_img_box">
                        <img src="{% static 'user/images/illus.png' %}" alt="">
                    </div>
                    <h3 class="ml-1">Overall Progress</h3>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ progress }}%;" aria-valuenow="25" aria-valuemin="0"
                        aria-valuemax="100">{{ progress }}%</div>
                </div>
                <p>{{ progress }}%</p>
            </div>
            {% endwith %}
        </div>
        {% endfor %}
    {% endif %}
    </section>

{% endblock content %}

language/templates/language/manage.html
{% extends "user/base.html" %}
{% load static %}
{% load custom_filter_tags %}
{% block content %}
<section class="content">
{% if user.profile.languages.all %}
        <div class="first-text">
            <h1 class="lead">My&nbsp&nbspCourses</h1>
        </div>
        {% for course in user.profile.languages.all %}
            <div class="mt-5">
                <a href="{% url 'single' course.id %}" style="color:black;"> <h2>{{  course.name }}</h2></a>
                {% with progress=user.result_set.all|calculate:course %}
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ progress }}%;" aria-valuenow="25" aria-valuemin="0"
                        aria-valuemax="100">{{ progress }}%</div>
                </div>
                {% endwith %}
                <div class="links mt-3">
                    <a href="{% url 'reset' course.id %}" class="btn btn-danger">Reset Progress</a>
                    <a href="{% url 'remove' course.id %}" class="btn btn-info mr-3">Remove</a>
                </div>
            </div>
        {% endfor %}
{% endif %}


{% if languages.count > user.profile.languages.count %}
     <div class="first-text mt-5">
            <h1 class="lead">Available&nbsp&nbspCourses</h1>
        </div>
    {% for language in languages %}
        {% if language not in user.profile.languages.all %}
             <div class="mt-5">
                <a href="{% url 'register-single' language.id %}" style="color:black;"> <h2>{{ language.name }}</h2></a>
                <div class="links mt-3">
                    <a href="{% url 'add' language.id %}" class="btn btn-info mr-3">Add to My Courses</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
</section>
{% endblock content %}

language/templates/language/result.html
{% extends "user/base.html" %}
{% load static %}
{% load custom_filter_tags %}
{% block content %}
    <section class="content">
        <div class="first-text">
            <h1 class="lead">Result</h1>
        </div>
        <div class="content_box d-flex">
            <div class="content_box_one">
                <h3>Answers</h3>
                <div class="alphabet_box">
                    {% for question in object.study_material.question_set.all %}
                        <h4>{{ forloop.counter }}.) {{ question.text }}</h4>
                        {% for option in question.answeroptions_set.all %}
                            {% if option.is_correct %}
                                <label>({{ forloop.counter|alphabet }}) {{ option.options_text }}&nbsp&nbsp</label><i class="fas fa-check" style="color: green;"></i><br>
                                {% else %}
                                <label>({{ forloop.counter|alphabet }}) {{ option.options_text }}&nbsp&nbsp</label><i class="fas fa-times" style="color: red;"></i><br>
                                {% endif %}
                            {% endfor %}
                    {% endfor %}
                </div>
                <div class="mt-3">
                    <a href="{% url 'single' object.study_material.stage.language.id %}" class="btn btn-primary">Continue Learning</a>
                </div>

            </div>
            <div class="content_box_two">
                <div class="top d-flex align-items-end">
                    <div class="top_img_box">
                        <img src="{% static 'user/images/illus.png' %}" alt="">
                    </div>
                    <h3 class="ml-1">Score</h3>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ object.score }}%;" aria-valuenow="25" aria-valuemin="0"
                        aria-valuemax="100">{{ object.score }}%</div>
                </div>
                <p>{{ object.score }}%</p>
            </div>

        </div>
    </section>
{% endblock content %}

language/templates/language/search.html
{% extends "user/base.html" %}
{% load static %}
{% load custom_filter_tags %}
{% block content %}
    <section class="content">
        <div class="first-text">
            <h1 class="lead">You&nbsp&nbspSearched&nbsp&nbspfor&nbsp&nbsp{{ query }}</h1>
        </div>
        {% for language in objects %}
        <div class="border-bottom mt-5">
            <a href="{% url 'single' language.id %}" style="color:black;"><h1>{{ language.name }}</h1></a>
        </div>
        <div class="mt-2">
            {% if language.brief_description %}
            <p>Description: {{ language.brief_description }}</p>
            {% endif %}
        </div>
        <div class="links mt-3">
            <a href="{% url 'register-single' language.id %}" class="btn btn-info mr-3">Click To Register</a>
        </div>
        {% endfor %}
    </section>
{% endblock content %}

language/templates/language/single-language.html
{% extends "user/base.html" %}
{% load static %}
{% load custom_filter_tags %}
{% block content %}
<section class="content">
        <div class="first-text">
            <h1 class="lead">{{ language.name }}</h1>
        </div>
        <div class="mt-2">
            {% if language.brief_description %}
            <p>{{ language.brief_description|linebreaks }}</p>
            {% endif %}
        </div>
        <div class="content_box d-flex">
            <div class="content_box_one">

                <div class="row">
                    {% for stage in language.stage_set.all %}
                    <div class="col-lg-4 col-md-6 col-sm-6 co-12 mb-4 c_box_cover">
                        <h3>{{ stage.studymaterial.topic }}</h3>
                        <a href="{% url 'study' stage.studymaterial.id %}">
                            <div class="c_box">
                                {{ stage.studymaterial.text|shrink }}...  <b> Click to learn</b>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% with progress=user.result_set.all|calculate:language %}
            <div class="content_box_two">
                <div class="top d-flex align-items-end">
                    <div class="top_img_box">
                        <img src="{% static 'user/images/illus.png' %}" alt="">
                    </div>
                    <h3 class="ml-1">Overall Progress</h3>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ progress }}%;" aria-valuenow="25" aria-valuemin="0"
                        aria-valuemax="100">{{ progress }}%</div>
                </div>
                <p>{{ progress }}%</p>
            </div>
            {% endwith %}
        </div>
    </section>
{% endblock content %}

language/templates/language/study_material.html
{% extends "user/base.html" %}
{% load static %}
{% load custom_filter_tags %}
{% block content %}
<section class="content">
        <div class="first-text">
            <h1 class="lead">Learn&nbsp&nbsp{{ material.stage.language.name }}</h1>
        </div>
        <div class="content_box d-flex">
            <div class="content_box_one">
                <h3>{{ material.topic }}</h3>
                <div class="alphabet_box">
                    {{ material.text|linebreaks }}
                </div>
        {% if material.audio %}
            <div class="audio-div mt-4">
                <h3 class="mb-3">Listen:</h3>
                <audio src="{{ material.audio.url }}" controls>Audio element not supported by your browser</audio>
            </div>
        {% endif %}
        <div class="questions mt-4">
                                {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
            <h3 class="mb-3">Questions:</h3>
            <div class="question">
                <form action="{% url 'analyze' material.id %}" method="POST">
                    {% csrf_token %}
                {% for question in material.question_set.all %}
                    <p class="question-text">{{ forloop.counter }}. {{ question.text }}</p>
                    {% if question.audio %}
                    <div class="audio-div">
                        <audio src="{{ question.audio.url }}" controls>Audio element not supported by your browser</audio>
                    </div>
                    {% endif %}
                    {% with name=question.id %}
                    {% for answer in question.answeroptions_set.all %}
                        <div class="options">
                        <label for="{{ answer.id }}">({{ forloop.counter|alphabet }}) {{ answer.options_text }}</label>
                        <input type="radio" id="{{ answer.id }}" name="{{ name|string }}" value="{{ answer.id }}">
                        </div>
                    {% endfor %}
                    {% endwith %}
                {% endfor %}
                    <button class="log_button btn mt-4">Submit</button>
                    <p>{{ error }}</p>
                </form>
            </div>
        </div>
            </div>
            <div class="content_box_two">
                <div class="top d-flex align-items-end">
                    <div class="top_img_box">
                        <img src="{% static 'user/images/illus.png' %}" alt="">
                    </div>
                    <h3 class="ml-1">Course Progress</h3>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" {% if not result %} style="width:0%;"{% else %} style="width:{{ result.score }}%; {% endif %}aria-valuenow="25" aria-valuemin="0"
                        aria-valuemax="100">{% if not result %} 0% {% else %} {{ result.score }}% {% endif %}</div>
                </div>
                <p>{% if not result %} 0% {% else %} {{ result.score }}% {% endif %}</p>
            </div>
        </div>

    </section>
{% endblock content %}